# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zpEw9IGshfPAlOqspBGTQwsNW3cN5vkL
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
import pickle
from sklearn.datasets import load_digits

# Load model
with open("model.pkl", "rb") as f:
    model = pickle.load(f)

# Load digits dataset
digits = load_digits()

st.title("🔢 Klasifikasi Angka Tulisan Tangan")

index = st.slider("Pilih index gambar:", 0, len(digits.images)-1, 0)
image = digits.images[index]
data = digits.data[index].reshape(1, -1)

st.image(image / 16.0, caption=f"Label Asli: {digits.target[index]}", width=150)
if st.button("Prediksi"):
    pred = model.predict(data)[0]
    st.success(f"Model memprediksi angka: {pred}")