# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d1zO9agGe1nlpNP-jexWV-vyLBJ69W21
"""

from sklearn.datasets import load_digits
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import pickle

# Load dataset
digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, random_state=42)

# Train model
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Simpan model
with open("model.pkl", "wb") as f:
    pickle.dump(model, f)